language: node_js
node_js:
  - "12.0.0"

cache: yarn

stages:
  - test

jobs:
  include:
    - name: "Linter"
      stage: test
      script: yarn lint
    - name: "Unit tests"
      stage: test
      script: yarn test
