language: node_js
node_js:
  - 10
  - 11

cache: yarn

stages:
  - test

jobs:
  include:
    - name: lint
      stage: test
      script: yarn lint
    - name: test
      stage: test
      script: yarn test
